<a href="https://colab.research.google.com/github/Tosin-doc/Basic-Pytorch-Functions/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1R6-UAttiQHZl4k65953hwzZzT8uaTRik')

# Pytorch Functions You Should Know

A short introduction about PyTorch and about the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

Before we begin, let's install and import PyTorch

In [2]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [3]:
# Import torch and other required modules
import torch

## Function 1 - torch.addcmul
torch.addcmul function helps us in element wise multiplication of the passed in tensors (tensor 1 and tensor 2) take a fraction of it by multiplying with a constant value and summing up the resultant value with the input tensor.

The function can be represented as a formula as follows.

<math xmlns="http://www.w3.org/1998/Math/MathML">
  <msub>
    <mtext>out</mtext>
    <mi>i</mi>
  </msub>
  <mo>=</mo>
  <msub>
    <mtext>input</mtext>
    <mi>i</mi>
  </msub>
  <mo>+</mo>
  <mtext>value</mtext>
  <mo>&#xD7;</mo>
  <msub>
    <mtext>tensor1</mtext>
    <mi>i</mi>
  </msub>
  <mo>&#xD7;</mo>
  <msub>
    <mtext>tensor2</mtext>
    <mi>i</mi>
  </msub>
</math>


Function takes in input, value, tensor1 and tensor2 as inputs, create an output

In [4]:
#Example 1
# Input Tensor
input_t = torch.eye(1,2)

#Value
value=0.4

#Tensor 1 & 2
tensor1 = torch.eye(1,2)
tensor2 = torch.eye(2,1)

# Function
torch.addcmul(input_t,value,tensor1,tensor2)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: UserWarning: This overload of addcmul is deprecated:
	addcmul(Tensor input, Number value, Tensor tensor1, Tensor tensor2, *, Tensor out)
Consider using one of the following signatures instead:
	addcmul(Tensor input, Tensor tensor1, Tensor tensor2, *, Number value, Tensor out) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  del sys.path[0]


tensor([[1.4000, 0.0000],
        [1.0000, 0.0000]])

In the above example we use identity matrix to understand the functionality of the torch.addmul() function.It should note that the tensor1 and tensor2 is multiplied element wise before being multiplied with the user inputted value. Shape of tensor1 and tensor2 should have size which can be either broadcasted to match either of those are will result in an error.

In [5]:
# Example 2 - 
input_t = torch.randn(1,4)

#Value
value=0.4

#Tensor 1 & 2
tensor1 = torch.randn(1,4)
tensor2 = torch.randn(2,1)

# Function
torch.addcmul(input_t,value,tensor1,tensor2)

tensor([[-0.8645, -1.0327,  0.2428,  0.9353],
        [-1.1646, -1.0111,  0.2749,  0.6326]])

Step By Step Breakdown of the above Example

1. tensor1 and tensor2 are multiplied element wise
2. Value provided by the user is then multiplied element wise with the matrix resulting from above.

Input Tensor is then added to the result produced

In [6]:
# Example 3 - breaking (to illustrate when it breaks)
input_t = torch.randn(1,3)

#Value
value=0.4

#Tensor 1 & 2
tensor1 = torch.randn(1,4)
tensor2 = torch.randn(3,1)

# Function
torch.addcmul(input_t,value,tensor1,tensor2)


RuntimeError: ignored

This function can break in two ways.

If the tensor1 and tensor2 element wise multiplication does not match in dimension.
The addition of input_t with the result produced doesn’t match in dimension.
In the Above case it failed because its not able to add [1,3] tensor with [3,4] produced by the multiplication is not possible.

Let's save our work using Jovian before continuing.

In [7]:
!pip install jovian --upgrade --quiet

In [8]:
import jovian

In [9]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tosin-doc/01-tensor-operations


'https://jovian.ai/tosin-doc/01-tensor-operations'

## Function 2 - torch.git

torch.gt function allows us in element wise comparision of the two inputs passed. The second argument can be a number that can be broadcasted to match the dimension of the first argument.

Mathematically represented as input > other

It takes in two arguments input and other

*  input is the tensor on which element wise comparison is need to be done.
*  other is the tensor value based on which the result is returned.

In [10]:

# Example 1 - Comparing with a scalar

#Input
input_t = torch.arange(0,10)

# Function
torch.gt(input_t,torch.tensor([4]))

tensor([False, False, False, False, False,  True,  True,  True,  True,  True])

In the above example the tensor input is compared with a single value 4 and the result is returned element wise.

In [11]:
# Example 2 - working

#Input
input_t = torch.arange(0,9).reshape(3,3)
other = torch.tensor([5,2,1,4,7,2,3,1,6]).reshape(3,3)
# Function
torch.gt(input_t,other)

tensor([[False, False,  True],
        [False, False,  True],
        [ True,  True,  True]])

In the above example we have two tensors of shape 3,3 and each element of input_t is compared with other tensor and the result is produced.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)

#Input
input_t = torch.arange(0,9).reshape(3,3)
other = torch.tensor([5,2,1,4,7,2,3,1,3,5]).reshape(2,5)
# Function
torch.gt(input_t,other)

RuntimeError: ignored

Shape of the input and other should match.

This function can be used to subset based on the condition of the other tensor

In [13]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tosin-doc/01-tensor-operations


'https://jovian.ai/tosin-doc/01-tensor-operations'

## Function 3 - torch.flatten()

As the name suggest the function is used to flatten or convert into a single row from different shape of the tensor. This functionality can also be altered by assigning the start and end dimension of the tensor to flatten it.

torch.flatten() takes in one argument and 2 optional argument

input is the tensor which is to be flattened
start_dimis the dimension along which flattening should be done
end_dim is the ending dimension along which flattening should be done.

In [14]:
# Example 1 - working
# Without any Keyword Arguments

input_t = torch.arange(10).reshape(2,5)
print("Displaying Input tensor")
display(input_t)
print(f'{input_t.shape} \n')

# Flattening the tensor
print("Displaying Flattened Tensor")

torch.flatten(input_t)


Displaying Input tensor


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

torch.Size([2, 5]) 

Displaying Flattened Tensor


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In this example the input tensor is of shape [2,5] which is then converted into [1,10] through flattening

In [15]:
# Example 2 - working
# With Keyword Argument start_dim

input_t = torch.arange(20).reshape(2,2,5)
print("Displaying Input tensor")
display(input_t)
print(f'{input_t.shape} \n')

# Flattening the tensor
print("Displaying Flattened Tensor")

torch.flatten(input_t,start_dim=1)

Displaying Input tensor


tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]])

torch.Size([2, 2, 5]) 

Displaying Flattened Tensor


tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

Explanation about example

In the above example input tensor is of shape [2,2,5] and since the tensor is flattened on shape 1 it returns a tensor of shape [2,10]

In [16]:
# Example 3 - breaking (to illustrate when it breaks)

input_t = torch.arange(10).reshape(2,5)
print("Displaying Input tensor")
display(input_t)
print(f'{input_t.shape} \n')

# Flattening the tensor
print("Displaying Flattened Tensor")

torch.flatten(input_t,start_dim=2)

Displaying Input tensor


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

torch.Size([2, 5]) 

Displaying Flattened Tensor


IndexError: ignored

The above example breaks because the input tensor is of shape [2,5] and the start dimension is specified as 2. But the value in this case should be between [-2,1].

This function can be used when we need to convert the image tensor into a linear unit.

In [17]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tosin-doc/01-tensor-operations


'https://jovian.ai/tosin-doc/01-tensor-operations'

## Function 4 - torch.clamp()

torch.clamp function is used to limit the value in the tensor to a needed limit, within the min and max value.

Mathematically this function can be represented as

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <msub>
    <mi>y</mi>
    <mi>i</mi>
  </msub>
  <mo>=</mo>
  <mrow data-mjx-texclass="INNER">
    <mo data-mjx-texclass="OPEN">{</mo>
    <mtable columnalign="left left" columnspacing="1em" rowspacing=".2em">
      <mtr>
        <mtd>
          <mtext>min</mtext>
        </mtd>
        <mtd>
          <mtext>if&#xA0;</mtext>
          <msub>
            <mi>x</mi>
            <mi>i</mi>
          </msub>
          <mo>&lt;</mo>
          <mtext>min</mtext>
          <mtext>&#xA0;</mtext>
          <msub>
            <mi>x</mi>
            <mi>i</mi>
          </msub>
        </mtd>
        <mtd>
          <mtext>if&#xA0;</mtext>
          <mtext>min</mtext>
          <mo>&#x2264;</mo>
          <msub>
            <mi>x</mi>
            <mi>i</mi>
          </msub>
          <mo>&#x2264;</mo>
          <mtext>max</mtext>
          <mtext>&#xA0;</mtext>
          <mtext>max</mtext>
        </mtd>
        <mtd>
          <mtext>if&#xA0;</mtext>
          <msub>
            <mi>x</mi>
            <mi>i</mi>
          </msub>
          <mo>&gt;</mo>
          <mtext>max</mtext>
        </mtd>
      </mtr>
    </mtable>
    <mo data-mjx-texclass="CLOSE" fence="true" stretchy="true" symmetric="true"></mo>
  </mrow>
</math>
 

torch.clamp takes in 3 arguments

*   input which is the tensor on which the clamp is to be applied
*   min the min value of the tensor after transformation
*   max the max value of the tensor after transformation


It should be noted the values already lying within the range is untouched.

In [18]:
# Example 1 - working
input_t = torch.randn(20)
display(input_t)

torch.clamp(input_t,-0.2,0.2)

tensor([ 0.0528, -1.7944,  1.4019,  1.9973,  1.4865,  3.2219,  0.8344,  0.5819,
        -0.3843, -1.1803, -2.0581, -0.2031, -0.7404,  1.0038,  1.5646,  0.4750,
         0.0927, -0.2654,  0.0426,  0.3310])

tensor([ 0.0528, -0.2000,  0.2000,  0.2000,  0.2000,  0.2000,  0.2000,  0.2000,
        -0.2000, -0.2000, -0.2000, -0.2000, -0.2000,  0.2000,  0.2000,  0.2000,
         0.0927, -0.2000,  0.0426,  0.2000])

In the above example the values are clamped to the min value of -0.2 and max of 0.2. the values that lie within the range are untouched.

In [19]:
# Example 2 - working
input_t = torch.randn(20).reshape(2,2,5)
print("Before Clamping")
display(input_t)

print("After Clamping")
display(torch.clamp(input_t,max=0.3))

Before Clamping


tensor([[[ 0.9760,  1.4290, -0.4873,  0.3712, -1.2290],
         [ 2.0886, -0.8333,  0.1474, -1.7361, -0.2043]],

        [[-0.0825, -1.4008,  1.1304, -0.0438,  0.9690],
         [-0.4801,  0.5569,  0.2388, -0.8573,  0.0413]]])

After Clamping


tensor([[[ 0.3000,  0.3000, -0.4873,  0.3000, -1.2290],
         [ 0.3000, -0.8333,  0.1474, -1.7361, -0.2043]],

        [[-0.0825, -1.4008,  0.3000, -0.0438,  0.3000],
         [-0.4801,  0.3000,  0.2388, -0.8573,  0.0413]]])

In this example only the max value is clamped and the lower-bound is untouched.

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
input_t = torch.randn(20).reshape(2,2,5)
print("Before Clamping")
display(input_t)

print("After Clamping")
display(torch.clamp(input_t))


Before Clamping


tensor([[[ 0.1515,  0.5376,  0.3773, -0.5586,  0.8383],
         [ 1.7634, -2.2353,  0.5859, -1.0368, -0.3764]],

        [[-0.0500, -0.8921, -0.1028, -1.0448, -0.1495],
         [-1.1194,  1.6196,  0.5938,  1.5513,  0.9477]]])

After Clamping


RuntimeError: ignored

This function breaks without max or min being passed to the argument.

Can be used in optimizers to clip the value of the produced tensors.

In [21]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tosin-doc/01-tensor-operations


'https://jovian.ai/tosin-doc/01-tensor-operations'

## Function 5 - torch.cat()

torch.cat concatenates the sequence of tensors in the given dimension.All tensors must have the same shape or be empty.

torch.cat takes in 2 arguments

tensors - The input tensor sequence which can be 2 or more tensors
dim - The dimension along which the tensor should be concatenated.

In [22]:
# Example 1 - working
tensor1 = torch.arange(1,11).reshape(2,5)
tensor2 = torch.arange(11,21).reshape(2,5)

torch.cat((tensor1,tensor2), dim=1)

tensor([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
        [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In the above case we have two tensor with shape 2,5 and trying to concatenate along the row. So this just horizontally stacks the tensor over the tensor1.

In [23]:
# Example 2 - working

tensor1 = torch.arange(1,21).reshape(2,2,5)
tensor2 = torch.arange(21,41).reshape(2,2,5)

torch.cat((tensor1,tensor2), dim=1)

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20],
         [31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40]]])

In the above 3 dimensional tensor stacking of the values have happened along the row. each row value is exapaned to tensor.

In [24]:
# Example 3 - breaking (to illustrate when it breaks)

tensor1 = torch.arange(1,21).reshape(2,2,5)
tensor2 = torch.arange(21,41).reshape(2,2,5)

torch.cat((tensor1,tensor2), dim=3)

IndexError: ignored

Dimension did not match in this case. So the function fails. should be within the range of [-3,2]

In [25]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tosin-doc/01-tensor-operations


'https://jovian.ai/tosin-doc/01-tensor-operations'

## Conclusion

So In this notebook we have seen some exciting function which can ease out the speed of experimenting during model development. This is by no means the exhaustive list of functions available. For more details check out official documentation.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html


In [26]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tosin-doc/01-tensor-operations


'https://jovian.ai/tosin-doc/01-tensor-operations'